import {
  Wallet,
  Landmark,
  PiggyBank,
  CreditCard,
  Banknote,
  Coins,
  Building2,
  Home,
  Car,
  Utensils,
  ShoppingCart,
  HeartPulse,
  GraduationCap,
  Plane,
  Gift,
  Dog,
  Briefcase,
  Smartphone,
  Tv,
  Dumbbell,
  Receipt,
  TrendingUp,
  Tag,
  type LucideIcon,
} from "lucide-react";

export const ICON_OPTIONS: { value: string; label: string; icon: LucideIcon }[] = [
  { value: "wallet", label: "Carteira", icon: Wallet },
  { value: "landmark", label: "Banco", icon: Landmark },
  { value: "piggy-bank", label: "Poupança", icon: PiggyBank },
  { value: "credit-card", label: "Cartão", icon: CreditCard },
  { value: "banknote", label: "Dinheiro", icon: Banknote },
  { value: "coins", label: "Moedas", icon: Coins },
  { value: "building", label: "Empresa", icon: Building2 },
  { value: "home", label: "Casa", icon: Home },
  { value: "car", label: "Carro", icon: Car },
  { value: "food", label: "Alimentação", icon: Utensils },
  { value: "cart", label: "Compras", icon: ShoppingCart },
  { value: "health", label: "Saúde", icon: HeartPulse },
  { value: "education", label: "Educação", icon: GraduationCap },
  { value: "travel", label: "Viagem", icon: Plane },
  { value: "gift", label: "Presente", icon: Gift },
  { value: "pet", label: "Pet", icon: Dog },
  { value: "work", label: "Trabalho", icon: Briefcase },
  { value: "phone", label: "Assinatura/App", icon: Smartphone },
  { value: "entertainment", label: "Lazer", icon: Tv },
  { value: "fitness", label: "Academia", icon: Dumbbell },
  { value: "bill", label: "Conta/Boleto", icon: Receipt },
  { value: "investment", label: "Investimento", icon: TrendingUp },
  { value: "other", label: "Outro", icon: Tag },
];

export function getIcon(value: string | null | undefined): LucideIcon {
  return ICON_OPTIONS.find((option) => option.value === value)?.icon ?? Tag;
}
